### ISSUE TITLE
Runway naming & selection issue

### ISSUE THREAD

**Issue by tdcxs** [embention/ISS#11]
We noticed that runways allocation is unclear.
Currently, there is an index issue : they go from Runway 0 to 2 in Veronte app whereas they go from 1 to 3 in PDIBuilder.
Also, we cannot select which runway is concerned in Veronte App. 
Maybe it would be clearer if instead of a figure it would be the name of the phase that would be attached to the runway.

**Comment by jmt1** [comment]
Hello, thank you for using this way of communication, after an internal discussion it has been decided that we will keep this way of communication but you will have access to your repository directly, not in this public.
This is under development.
This issue is underdevelopment right now we expect deliver this month.
Thank you for your time, you will hear from us soon.
