### ISSUE TITLE
Mapping tools

### ISSUE THREAD

**Issue by tdcxs** [embention/ISS#13]
### Description of the problem

It currently misses some tools to do mapping missions: 
- photogrammetry mission (already available in 6.4) 
- search and rescue mission (already available in 6.4)
- corridor mapping

**Comment by jmt1** [comment]
Hello, thank you for using this way of communication, after an internal discussion it has been decided that we will keep this way of communication but you will have access to your repository directly.
This is under development.
I can also inform you that this issue is already considered in the development plans.
Thank you for your time, you will hear from us soon.
