### ISSUE TITLE
VeronteLink managing VerontePDI Builder and VeronteHIL

### ISSUE THREAD

**Issue by tdcxs** [embention/ISS#15]
### Description of the problem

We can't use VerontePDI Builder and VeronteHIL at the same time. 
It is not convenient when creating a new configuration and debugging it in HIL.

Versions : 
- VeronteLink 6.1.13
- VerontePDI Builder 6.8.19
- VeronteHIL 6.8.6

**Comment by jmt1** [comment]
Hello, thank you for using this way of communication, after an internal discussion it has been decided that we will keep this way of communication but you will have access to your repository directly, not in this public.
This is under development.
This issue is underdevelopment right now to be able to use this programs at same time.
Thank you for your time, you will hear from us soon.
