### ISSUE TITLE
Mission buttons under widget

### ISSUE THREAD

**Issue by dvv1** [embention/ISS#17]
### Description of the problem

Al arrastrar el widget para colocarlo en la parte izquierda de la pantalla, la parte transparente del widget queda por encima de los botones de misión, de forma que no se pueden utilizar. El widget debería quedar por detrás de los botones en todo momento.

### Drag the downloaded zip, image and video

https://user-images.githubusercontent.com/91458218/178962097-fb32c743-df06-43ba-baf3-3bf287e5c31c.mp4

**Comment by jmt1** [comment]
Hello, thank you for using this way of communication, after an internal discussion it has been decided that we will keep this way of communication but you will have access to your repository directly, not in this public.
This is under development.
This issue is underdevelopment right now , and will be released very soon.
Thank you for your time, you will hear from us soon.
